import type { Metadata } from "next";
import Header from "@/components/Header";
import Buttons from "@/components/Buttons";
import Footer from "@/components/Footer";
import "./reset.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Buttons />
        <Footer />
      </body>
    </html>
  );
}
